endpoint: '{{proj.dbt_url}}/v2/accounts/{{proj.dbt_account_id}}/jobs/{{vars.job_id}}/run/'
external_integration: DBT_API_ACCESS_INTEGRATION
functions:
- raise_exception
- json_loads
- sleep
- json_dumps
headers: |-
  {
    "Authorization": "Token {{secrets.token}}"
  }
macro_libs:
- google_apis
- dbt_apis
payload: |-
  {%- set name = json_loads(_prehook)['summary'] -%}
  {"cause": "API Triggered by {{name}}"}
payload_format: json
posthook: '{{ check_dbt_job_status(_response,10,5) }}'
posthook_enable: true
posthook_return_output: true
prehook: '{{ get_events() }}'
prehook_enable: true
request_type: post
response_format: json
response_status_code_range:
- 200
- 299
secrets:
- alias: token
  secret: TEST1
type: procedure
variables:
- name: job_id
  test_value: '534772'
  type: text
