enable_posthook: false
enable_prehook: false
endpoint: https://www.googleapis.com/calendar/v3/calendars/{{ vars.google_account
  }}/events?maxResults={{vars.limit}}
external_integration: GOOGLE_APIS_ACCESS_INTEGRATION
headers: |-
  {
    "Authorization": "Bearer {{ secrets.oauth}}",
    "Accept":"application/json",
    "Content-type": "application/json"
  }
job_functions: []
job_macro_libs:
- test1
- test2
job_type: Procedure
job_variables:
- test_value: ywan160@gmail.com
  name: google_account
  type: Text
- test_value: '2'
  name: limit
  type: Text
payload_format: Json
request_type: GET
response_format: Json
secrets:
- alias: oauth
  secret: GOOGLE_OAUTH_SECRET
status_code_range:
- 100
- 299
store_response: true
