endpoint: https://www.googleapis.com/calendar/v3/calendars/{{ vars.google_account
  }}/events
external_integration: GOOGLE_APIS_ACCESS_INTEGRATION
functions:
- now
- json_dumps
headers: |-
  {
    "Authorization": "Bearer {{ secrets.oauth}}",
    "Accept":"application/json",
    "Content-Type": "application/json"
  }
macro_libs: []
payload: |-
  {
    "start": {
      "dateTime": "{{vars.startdt}}",
      "timeZone": "{{proj.timezone}}"
    },
    "end": {
      "dateTime": "{{now().isoformat()}}",
      "timeZone": "{{proj.timezone}}"
    },
    "summary": "{{vars.title}}"
  }
payload_format: json
posthook_enable: false
prehook: '{{ now() }}'
prehook_enable: true
request_type: post
response_format: json
response_status_code_range:
- 100
- 299
secrets:
- alias: oauth
  secret: GOOGLE_OAUTH_SECRET
- alias: gen
  secret: TEST1
- alias: gen2
  secret: TEST1
type: table_function
variables:
- name: title
  test_value: MyEvent
  type: text
- name: google_account
  test_value: ywan160@gmail.com
  type: text
- name: startdt
  test_value: '2024-02-04T09:00:00'
  type: text
- name: enddt
  test_value: '2024-02-06T17:00:00'
  type: text
