enable_posthook: true
enable_prehook: true
endpoint: '{{proj.dbt_url}}/v2/accounts/{{proj.dbt_account_id}}/jobs/{{vars.job_id}}/run/'
external_integration: DBT_API_ACCESS_INTEGRATION
headers: |-
  {
    "Authorization": "Token {{secrets.token}}"
  }
job_functions:
- raise_exception
- json_loads
- sleep
- json_dumps
job_macro_libs:
- google_apis
- test1
- test2
- dbt_apis
job_type: Procedure
job_variables:
- test_value: '534772'
  name: job_id
  type: Text
payload: |-
  {%- set name = json_loads(_prehook)['summary'] -%}
  {"cause": "API Triggered by {{name}}"}
payload_format: Json
posthook: '{{ check_dbt_job_status(_response,10,5) }}'
prehook: '{{ get_events() }}'
request_type: POST
response_format: Json
return_posthook_output: true
secrets:
- alias: token
  secret: TEST1
status_code_range:
- 200
- 299
store_response: false
