enable_posthook: false
enable_prehook: false
endpoint: '{{proj.dbt_url}}/v2/accounts/{{proj.dbt_account_id}}/runs/{{vars.run_info.data.id}}/'
external_integration: DBT_API_ACCESS_INTEGRATION
file_name: ''
file_ops_overwrite: false
file_ops_pack_unpack: false
file_ops_parallel: 4
headers: |-
  {
    "Authorization": "Token {{secrets.token}}"
  }
job_functions: []
job_macro_libs: []
job_type: Procedure
job_variables:
- debug_value: '{"data":{"id":254972454}}'
  name: run_info
  type: Variant(JSON)
payload: ''
payload_format: Json
posthook: ''
prehook: ''
request_type: GET
response_format: Json
return_posthook_output: false
secrets:
- alias: token
  secret: TEST1
status_code_range:
- 200
- 299
store_response: false
