endpoint: '{{proj.dbt_url}}/v2/accounts/{{proj.dbt_account_id}}/runs/{{vars.run_info.data.id}}/'
external_integration: DBT_API_ACCESS_INTEGRATION
functions: []
headers: |-
  {
    "Authorization": "Token {{secrets.token}}"
  }
macro_libs: []
payload_format: json
posthook_enable: false
prehook_enable: false
request_type: get
response_format: json
response_status_code_range:
- 200
- 299
secrets:
- alias: token
  secret: TEST1
type: procedure
variables:
- name: run_info
  test_value: '{"data":{"id":254972454}}'
  type: dict
