endpoint: https://www.googleapis.com/calendar/v3/calendars/{{ vars.google_account
  }}/events?maxResults={{vars.limit}}
external_integration: GOOGLE_APIS_ACCESS_INTEGRATION
functions: []
headers: |-
  {
    "Authorization": "Bearer {{ secrets.oauth}}",
    "Accept":"application/json",
    "Content-type": "application/json"
  }
macro_libs: []
payload_format: json
posthook_enable: false
prehook_enable: false
request_type: get
response_format: json
response_status_code_range:
- 100
- 299
secrets:
- alias: oauth
  secret: GOOGLE_OAUTH_SECRET
type: procedure
variables:
- name: google_account
  test_value: ywan160@gmail.com
  type: text
- name: limit
  test_value: '2'
  type: text
